server:
  port: 8080
  http:
    port: 80

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG

spring:
  cloud:
    gateway:
      routes:
        - id: messages
          uri: http://172.31.10.52:8082/
          predicates:
            - Path=/api/messages/**
        - id: api
          uri: http://172.31.10.52:8081/
          predicates:
            - Path=/api/**
        - id: content
          uri: https://artfx-images-001.s3.us-east-2.amazonaws.com/
          predicates:
            - Path=/content/**
        - id: messenger
          uri: http://artfx-messenger.s3-website.us-east-2.amazonaws.com/
          predicates:
            - Path=/messenger/**
        - id: superadmin
          uri: http://artfx-superadmin.s3-website.us-east-2.amazonaws.com/
          predicates:
            - Path=/**
